### ISSUE TITLE
usf-gansett-20230624T1200 issue

### ISSUE THREAD

**Issue by kbailey-noaa** [ioos/glider-dac#305]
https://gliders.ioos.us/erddap/tabledap/usf-gansett-20230624T1200.html

This dataset contains data predating the file start date of 6/24/2023.  Data begin 3/27/2023. But those data are already captured in a separate dataset: https://gliders.ioos.us/erddap/tabledap/usf-gansett-20230327T1200.html. 

Can you pls investigate / repair so that usf-gansett-20230624T1200 data actually begin 6/24/2023?

**Comment by kerfoot** [comment]
Since the previous deployment [usf-gansett-20230327T1200/](https://gliders.ioos.us/erddap/files/usf-gansett-20230327T1200/) appears to contain all of the relevant files, the fix for this is to remove all data provider files from [usf-gansett-20230624T1200](https://gliders.ioos.us/erddap/files/usf-gansett-20230624T1200/) that begin with 

    usf-ganset-2023032[78]*.nc

I have removed all of these files via the [data providers web app](https://gliders.ioos.us/providers/users/gcoos_dmac/deployment/64998c0673c9920009130fe8). The data set should update after the next ERDDAP data set reload event.

It would be much easier, quicker and cleaner for me to do this if I had access to the servers via dual factor authentication or VPN which, I believe, is how all Tetratech employees access the servers securely. There would be no difference in the access method and it would allow me to support @benjwadams by performing these types of operations (and many others) so that he can focus on more important tasking.

@kbailey-noaa can close this once you confirm that the data set has updated.

**Comment by kbailey-noaa** [comment]
Looks good, thanks!
