### ISSUE TITLE
Missing standard_names for DAC provided QARTOD QC variabes

### ISSUE THREAD

**Issue by kerfoot** [ioos/glider-dac#382]
I couldn't find an issue template for an issue such as this so I'm submitting it as a general issue....

The compliance checker is reporting missing standard_names for some/all of the QARTOD qc flag variables.  Here are the compliance reports for [bios_jack-20240812T1810](https://gliders.ioos.us/providers/users/rutgers/deployment/66bac21f7c54720008f0c753) and [ru36-20240821T1852](https://gliders.ioos.us/providers/users/rutgers/deployment/66c69b2b712796000b3c38b6) as examples.

There are standard names for these types of flags in the [CF standards](https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html).

**Comment by leilabbb** [comment]
The standard names are in the [system](https://github.com/ioos/glider-dac/blob/9f5abcfca6eb300f6a7506e4f2a2e0e67dd50692/glider_qc/glider_qc.py#L80-L106), but for the cases you cited, they are missing from the attribute list of the QARTOD variable, which needs further investigation.


For [bios_jack-20240812T1810](https://gliders.ioos.us/providers/users/rutgers/deployment/66bac21f7c54720008f0c753), the flags for density and salinity are missing because the valid_min and valid_max values are switched, causing the netCDF library to interpret them as NaNs.

For [ru36-20240821T1852](https://gliders.ioos.us/erddap/tabledap/ru36-20240821T1852.html), the QARTOD flags for conductivity, density, and salinity are missing because the standard_names are absent from the list of attributes.

**Comment by kerfoot** [comment]
It looks like there are still issues with standard_name/long_name attributes on QC variables added by the DAC team:

[ru36-20240821T1852](https://gliders.ioos.us/providers/users/rutgers/deployment/66c69b2b712796000b3c38b6)

I believe [at least one additional issue](https://github.com/ioos/glider-dac/issues/385) has been submitted by another provider.

What is the status on this?

**Comment by leilabbb** [comment]
Yes that is correct. Changes are been applied to datasets. Checkout [ERDDAP-ru36-20240821T1852](https://gliders.ioos.us/erddap/tabledap/ru36-20240821T1852.html)

> qartod_density_primary_flag {
>     Byte _FillValue 2;
>     String _Unsigned "false";
>     String dac_comment "QARTOD TESTS NOT RUN";
>     String flag_meanings "PASS NOT_EVALUATED SUSPECT FAIL MISSING";
>     Byte flag_values 1, 2, 3, 4, 9;
>     String ioos_category "Quality";
>     **String long_name "QARTOD Flat Line Test for sea_water_density";**
>     String references "https://gliders.ioos.us/files/Manual-for-QC-of-Glider-Data_05_09_16.pdf";
>     **String standard_name "aggregate_quality_flag";**
>     String units "1";
>     Byte valid_max 9;
>     Byte valid_min 1;
>   }

The compliance checker needs to run again to reflect changes.

**Comment by leilabbb** [comment]
The errors are still showing up in the compliance check report. The ticket will be closed once the report is updated.

**Comment by benjwadams** [comment]
Fixed by recent commits as mentioned in issue referenced.  Will need to address other potentially affected deployments.
